# Generated by Django 5.1.5 on 2025-02-24 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orientadores',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=255)),
                ('Senha', models.CharField(max_length=255)),
                ('Cor', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('acompanhante', models.CharField(blank=True, max_length=255, null=True)),
                ('curso', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=11)),
                ('data_agendada', models.DateTimeField()),
                ('data_registrado', models.DateTimeField(auto_now_add=True)),
                ('presenca', models.CharField(choices=[('0', 'Ausente'), ('1', 'Presente'), ('2', '')], default='0', max_length=1)),
                ('status', models.CharField(choices=[('0', 'Recusou'), ('1', 'Comprou'), ('2', 'Negociando'), ('3', '')], default='2', max_length=1)),
                ('observacoes', models.CharField(max_length=255)),
                ('orientador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_de_Agendamento.orientadores')),
            ],
        ),
        migrations.CreateModel(
            name='chamadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamadas', models.IntegerField()),
                ('atendidas', models.IntegerField()),
                ('data', models.DateTimeField(auto_now=True)),
                ('orientador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_de_Agendamento.orientadores')),
            ],
        ),
    ]
