# Generated by Django 5.1.4 on 2025-01-23 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_de_Agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='Orientador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_de_Agendamento.orientadores'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Status',
            field=models.CharField(max_length=2),
        ),
    ]
