# Generated by Django 5.1.5 on 2025-02-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_de_Agendamento', '0002_chamadas_horario_alter_chamadas_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamadas',
            name='horario',
            field=models.TimeField(),
        ),
    ]
