# Generated by Django 5.1.4 on 2025-01-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_de_Agendamento', '0002_alter_clientes_orientador_alter_clientes_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='Acompanhante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
