# Generated by Django 5.1.4 on 2025-01-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_de_Agendamento', '0003_alter_clientes_acompanhante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='Celular',
            field=models.CharField(max_length=11),
        ),
    ]
