# Generated by Django 5.1.5 on 2025-02-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_de_Agendamento', '0003_alter_chamadas_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agendamentos', models.IntegerField(default=0)),
                ('data', models.DateField()),
            ],
        ),
    ]
