# Generated by Django 5.1.4 on 2025-01-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_de_Agendamento', '0004_alter_clientes_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='Presenca',
            field=models.CharField(choices=[('0', 'Ausente'), ('1', 'Presente')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Status',
            field=models.CharField(choices=[('0', 'Recusou'), ('1', 'Comprou'), ('2', 'Negociando')], default='2', max_length=1),
        ),
    ]
